language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U mypy
# command to run tests
script:
  - mypy scsync.py --ignore-missing-imports
  - python3 -m unittest -v tests/packets.py
